### PR TITLE
Fix plant drop handling

### PR DESCRIPTION
**Pull request by Thomas--S**
(especially noticeable for pineapple)

Tested with the most common plants.

### CODE REVIEW

**Comment by joe7575** [comment]
This changes the behaviour (more output) and the mod will be no longer 0.4.17 complient, right?

**Comment by Thomas--S** [comment]
In case of pineapples, output is drastically reduced and in general, the output is the same as when player digs the plant manually.

Apart from https://github.com/minetest/minetest/pull/7592, `get_node_drops` is compatible with 0.4.x versions, so I'd expect my change to be compatible with 0.4.17; although I didn't test it.

**Comment by joe7575** [comment]
From lua_api.txt:
```
* `minetest.get_node_drops(nodename, toolname)`
    * Returns list of item names.
    * **Note**: This will be removed or modified in a future version.
```

**Comment by joe7575** [comment]
> the output is the same as when player digs the plant manually
Yes, is this not too much, as you will always get more seed than needed?

**Comment by Thomas--S** [comment]
> You provide more than only the nodename

The documentation for this function was inaccruate in the times of Minetest 0.4.x, but the actual implementation accepts a node table as argument since 0.4.17. If compatibility with 0.4.16 is desired, I can chage it to use `node.name`.

https://github.com/tenplus1/minetest/blob/0.4.17/builtin/game/item.lua#L181

> Yes, is this not too much, as you will always get more seed than needed?

The current hardcoded values of the bot also provide more seed than needed; you either get two seeds and one crop or one seed and two crops.

While these values may work fine for most plants (i.e. they behave very similiar to the correct drop values), they aren't suited for some other plants. So, in general, it seems to me that it would be best to use the real drop property as intended by the authors of the farming mods.

**Comment by joe7575** [comment]
> While these values may work fine for most plants (i.e. they behave very similiar to the correct drop values), they aren't suited for some other plants. So, in general, it seems to me that it would be best to use the real drop property as intended by the authors of the farming mods.

Yes, you are right.Your code is much cleaner.
I did not use the function `minetest.get_node_drops(nodename, toolname)` because of the Note:
`This will be removed or modified in a future version.`

But today it is the better way.

**Pull request merged**
