### PR TITLE
Fix disconnected bot after Server-Crash (via LBM)

### PR DESCRIPTION
**Pull request by nixnoxus**
This is an alternative PR to #21

the 2nd commit https://github.com/joe7575/signs_bot/commit/9e99c40eee337d97a368586f0f4f353c6fcd8bba is optional and a matter of taste

Tested as described in the above PR

### CODE REVIEW

**Comment by joe7575** [comment]
Looks much better :)
But is the `tubelib2.walk_over_all` really necessary?
I did not test it, but why not removing all artefacts simply by adding "signs_bot:robot", "signs_bot:robot_foot", and "signs_bot:robot_leg" to the LBM?

**Comment by nixnoxus** [comment]
With the loop 'tubelib2.walk_over_all' I check if the robot is still connected to the box. 

If I omit this check, then the robots that are connected to the box are also removed. If now the server is terminated (clean with SIGTERM)  and restarted, the following happens after the player connection:
All robots are removed but the 'still connected' ones continue to work invisibly (harvest & seed). Only when they move they become visible again.

My problem is to find the `mem` of the corresponding box to compare `mem.robot_pos` with the current robot `pos`. Only if there is no match here, the robot is considered 'disconnected' and can be removed.

I had another approach at first:
- Save `base_pos` as meta at the robot.
the consequence:
- Every time the robot moves, I would have to delete `base_pos` of the old node and set it to the new node.

This approach I had then discarded because I found your LBM approach simpler and cleaner.

**Comment by nixnoxus** [comment]
Addendum to the 2nd commit https://github.com/joe7575/signs_bot/pull/22/commits/9e99c40eee337d97a368586f0f4f353c6fcd8bba

I didn't like my line:
```
signs_bot.remove_robot({robot_pos = pos})
```
`signs_bot.remove_robot` expects `mem` as argument. For code maintenance it is surely better to assume within the function that it really is a complete `mem` structure.

**Comment by joe7575** [comment]
> If I omit this check, then the robots that are connected to the box are also removed. If now the server is terminated (clean with SIGTERM) and restarted, the following happens after the player connection: All robots are removed but the 'still connected' ones continue to work invisibly (harvest & seed). Only when they move they become visible again.

But this can be solved by automatically replacing the bot after the box gets loaded:
- A bot removes itself via LBM
- A box replaces the bot via LBM (a few seconds later)

**Comment by nixnoxus** [comment]
> > If I omit this check, then the robots that are connected to the box are also removed. If now the server is terminated (clean with SIGTERM) and restarted, the following happens after the player connection: All robots are removed but the 'still connected' ones continue to work invisibly (harvest & seed). Only when they move they become visible again.
> 
> But this can be solved by automatically replacing the bot after the box gets loaded:
> 
>     * A bot removes itself via LBM
> 
>     * A box replaces the bot via LBM (a few seconds later)

i tried the restore bot through the box (commit: https://github.com/joe7575/signs_bot/pull/22/commits/b4c3fc4e836a710e8c232fc9234412fea5b983bf).
The problem is here again that the `mem` data after a server crash are chronologically before the world data. This leads to problems when constructing and farming.

Instead of restoring the bots from the possibly outdated data I tried another approach in the LBM (commit: https://github.com/joe7575/signs_bot/pull/22/commits/202b67628ab88371d7a051034a786755911f9e90):

- step 1: mark bot 'syncing'
 - robot waits 2 seconds for step 3
 - box waits 1 second for step 2
- step 2: box unmark a found robot
- step 3: remove still marked robots

**Comment by nixnoxus** [comment]
I like the first version(s) with `tubelib2.walk_over_all` best because of the simplicity.
I could add a second optional parameter `key` (and maybe a third `value`) to `tubelib2.walk_over_all` to filter specific mem's.
For example:
```lua
tubelib2.walk_over_all(callback, "robot_pos')
```

**Comment by nixnoxus** [comment]
ping @joe7575 

I think the best solution would be the first one https://github.com/joe7575/signs_bot/pull/22/commits/9878d58dbf6471486e5b51d5700adb01eadc86a6 plus an optional paramete key in tubelib2.walk_over_all

An alternative solution where the current (3-step-way) in https://github.com/joe7575/signs_bot/pull/22/commits/202b67628ab88371d7a051034a786755911f9e90

Or do you have another idea?

**Comment by joe7575** [comment]
> I think the best solution would be the first one [9878d58](https://github.com/joe7575/signs_bot/commit/9878d58dbf6471486e5b51d5700adb01eadc86a6) plus an optional paramete key in tubelib2.walk_over_all

Yes, I believe this is the best solution

**Comment by nixnoxus** [comment]
Thanks :)

**Pull request merged**
